name: run bash

on:
  push:
    branches: [ main ]

jobs:
  runBash:

    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v1
    - name: execute
      run: bash ./bash.sh
    - name: sleep
      run: sleep 10m     
    - name: execute
      run: bash ./bash.sh
    - name: sleep
      run: sleep 10m
    - name: execute
      run: bash ./bash.sh
    - name: sleep
      run: sleep 10m
    - name: execute
      run: bash ./bash.sh
    - name: sleep
      run: sleep 10m
    - name: execute
      run: bash ./bash.sh
    - name: sleep
      run: sleep 10m
    - name: execute
      run: bash ./bash.sh
    - name: sleep
      run: sleep 10m
    - name: execute
      run: bash ./bash.sh
      
