name: run bash1

on:
  push:
    branches: [ main ]

jobs:
  runBash:

    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v1
    - name: execute
      run: |
        apt-get install neofetch
        neofetch
